[project]
name = "impmagic"
version = "0.1.3"
description = "Librairie pour l'importation optimisé de module python"
mainfile = "__init__.py"
requires-python = ">=3.6"

[project.metadata]
authors = ["ZephyrOff"]
maintainers = []
readme = "README.md"
license = "MIT License"
license_file = "LICENSE"
keywords = ["import","module","zephyroff"]
classifiers = ["Development Status :: 5 - Production/Stable", "Environment :: Console", "License :: OSI Approved :: MIT License", "Programming Language :: Python :: 3"]
copyright = ""

[project.urls]
changelog = ""
homepage = "https://github.com/ZephyrOff/impmagic"
documentation = "https://github.com/ZephyrOff/impmagic"

[project.dependencies]

[project.dependencies.windows]

[project.dependencies.linux]

[project.build]
packages = ["inspect", "sys", "os"]
includes = ["impmagic"]
excludes = []
include_files = []
optimize = 0
no_compress = false
GUI = false
icon = ""

[project.wheel]
platforms = "ALL"

[project.wheel.entry_points]
console_scripts = []
